/**
 * Auto-generated by `agent-bundle build`.
 * Source: agent-bundle.yaml
 *
 * Do not edit — re-run `agent-bundle build` to regenerate.
 */

import { resolve } from "node:path";

import { loadBundleConfig } from "../../../src/cli/load-bundle-config.js";
import { defineAgent } from "../../../src/agent/define-agent.js";
import { loadAllSkills } from "../../../src/skills/loader.js";
import { generateSystemPromptTemplate } from "../../../src/agent-loop/system-prompt/generate.js";

const bundleDir = resolve(import.meta.dirname, "..");

const config = await loadBundleConfig(resolve(bundleDir, "agent-bundle.yaml"));

const skills = await loadAllSkills(config.skills, bundleDir);

const systemPrompt = generateSystemPromptTemplate({
  basePrompt: config.prompt.system,
  skills: skills.map((s) => ({
    name: s.name,
    description: s.description,
    sourcePath: s.sourcePath,
  })),
});

export const agent = defineAgent({
  name: config.name,
  sandbox: config.sandbox,
  model: config.model,
  systemPrompt: systemPrompt,
  variables: config.prompt.variables as [],
});
